sudo: false
language: c
compiler:
  - clang
  - gcc

env:
  global:
    - IOTC_BSP_TLS=mbedtls
    - IOTC_MAKETARGET=tests
  matrix:
    - PRESET=ARM_REL
      IOTC_MAKETARGET="utests"

    - PRESET=ARM_REL_MIN
          IOTC_MAKETARGET="utests"

    - PRESET=POSIX_DEV
    - PRESET=POSIX_DEV_MIN

    - PRESET=POSIX_REL
    - PRESET=POSIX_REL_MIN

    - PRESET=FREERTOS_POSIX_DEV
      BEFORE_SCRIPT_ACTION="make PRESET=FREERTOS_POSIX_REL prereqs"

    - PRESET=FREERTOS_POSIX_REL
      BEFORE_SCRIPT_ACTION="make PRESET=FREERTOS_POSIX_REL prereqs"

    # WOLFSSL Tests
    - PRESET=POSIX_DEV
      IOTC_BSP_TLS=wolfssl

    - PRESET=POSIX_REL
      IOTC_BSP_TLS=wolfssl

    - PRESET=POSIX_THREADING_REL
    # - PRESET=POSIX_UNSECURE_REL
    #   IOTC_BSP_TLS=""

    - TESTS=fuzztests
      PRESET=FUZZ_TESTS
      IOTC_BSP_TLS=""
      IOTC_MAKETARGET="fuzz_tests"
      CXX=clang++

    - PRESET=ZEPHYR

cache:
    apt
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - qemu-system
      - libc6:i386
      - expect
      - device-tree-compiler
      - gperf
      - dfu-util
      - xz-utils
        #  - python3-pip
        #  - python3-setuptools
        #  - python3-wheel
        #  - python3-pyelftools
matrix:
  exclude:
    - compiler: clang
      env: PRESET=ARM_REL_MIN IOTC_MAKETARGET="utests"
    - compiler: clang
      env: PRESET=ARM_REL IOTC_MAKETARGET="utests"
    - compiler: gcc
      env: TESTS=fuzztests PRESET=FUZZ_TESTS IOTC_BSP_TLS="" IOTC_MAKETARGET="fuzz_tests" CXX=clang++
    - compiler: gcc
      env: PRESET=POSIX_DEV IOTC_BSP_TLS=wolfssl
    - compiler: gcc
      env: PRESET=POSIX_REL IOTC_BSP_TLS=wolfssl
before_script:
  # https://wiki.ubuntu.com/SecurityTeam/Roadmap/KernelHardening#ptrace_Protection
  - "if [[ ! $TESTS == 'fuzztests' ]]; then
        if [[ $CC == *'clang'* ]]; then export CC='clang-3.8'; fi;
     else
        echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope;
     fi"
  - "if [[ $IOTC_BSP_TLS == 'wolfssl' ]]; then
      git clone -b v3.15.3-stable https://github.com/wolfSSL/wolfssl $HOME/build/GoogleCloudPlatform/iot-edge-sdk-embedded-c/third_party/tls/wolfssl;
    fi;"
  - "$BEFORE_SCRIPT_ACTION"
script:
  - "set -e"
  - "cd $HOME/build/GoogleCloudPlatform/iot-edge-sdk-embedded-c"
  - "if [[ $IOTC_BSP_TLS == 'wolfssl' ]]; then
       expect res/travis/travis_build_wolfssl.expect make PRESET=$PRESET IOTC_DEBUG_OUTPUT=0 $IOTC_MAKETARGET;
     else
       expect res/travis/travis_build_mbedtls.expect make PRESET=$PRESET IOTC_DEBUG_OUTPUT=0 $IOTC_MAKETARGET;
     fi;"
  - "if [[ ! $CC == 'gcc' && ! $TESTS == 'fuzztests' ]]; then
        if [[ $PRESET == 'FREERTOS_POSIX_REL' || $PRESET == 'FREERTOS_POSIX_DEV' ]]; then
                make -C examples/freertos_linux/Linux_gcc_gcp_iot IOTC_CLIENT_LIB_PATH=../../../bin/freertos-linux IOTC_BSP_TLS=$IOTC_BSP_TLS;
        else
                make -C examples/mqtt_logic_producer IOTC_CLIENT_LIB_PATH=../../bin/linux IOTC_BSP_TLS=$IOTC_BSP_TLS;
        fi;
    fi;"
